---
title: "total_tube_growth_results"
author: "Gabrielle Languedoc"
date: "25/11/2021"
output: pdf_document
---

#### Load required libraries and data set

```{r warning = FALSE, message = FALSE}

library(mgcv)
library(fitdistrplus)
library(goft)
library(gamlss)
library(here)
library(patchwork)
library(LambertW)
library(scales)
library(viridis)
library(performance)
library(dplyr) 
library(tidyverse)
library(readr)

# import data set
tube_growth <- read_csv("tube-growth.csv")


```

#### Cleaning Data Sheet

```{r warning = FALSE, message = FALSE}

# Manipulated data for intial visualization
clean_growth <- tube_growth %>%
select(total_growth, treatment) 

# Manipulated data for GAMLSS Model (Important note; Could not get the model to run using worm_id and string_loss as factors. This is likely because of the small sample size (N=90) creating to much noise)
model_growth <- tube_growth %>%
  dplyr::select(c(treatment,total_growth,mortality, amt_cut_mm, worm_id)) %>%
  mutate(worm_id = as.factor(worm_id))

  
```

### Visualizing Total Tube Growth Data with a boxplot
```{r warning = FALSE, message = FALSE}
#colour version
my_cols = c("low_salinity" = "#6300A7FF", "high_temp" = "#C03A83FF", "control" = "#F58C46FF")

ggplot(clean_growth, aes(x = treatment, y = total_growth, fill = treatment)) +
  geom_boxplot(alpha = 0.8) + 
  theme_classic() +
  ylab("Total Tube Growth (mm)") +
  xlab("Treatment") +
  scale_fill_manual(values = my_cols) +
  scale_colour_manual(values = my_cols) +
  theme(legend.position="none") +
  scale_x_discrete(labels = c('Control','Temperature','Salinity'))

ggsave(plot = last_plot(), filename = "total_tube_growth_boxplot_colourized.pdf")

#grey scale version
my_cols_grey = c("low_salinity" = "grey70", "high_temp" = "grey50", "control" = "grey30")
ggplot(clean_growth, aes(x = treatment, y = total_growth, fill = treatment)) +
  geom_boxplot(alpha = 0.8) + 
  theme_classic() +
  ylab("Total Tube Growth (mm)") +
  xlab("Treatment") +
  scale_fill_manual(values = my_cols_grey) +
  scale_colour_manual(values = my_cols_grey) +
  theme(legend.position="none") +
  scale_x_discrete(labels = c('Control','Temperature','Salinity'))

ggsave(plot = last_plot(), filename = "total_tube_growth_boxplot_greyscale.pdf")

```
### Finding Mean Values for Each Treatment

```{r warning = FALSE, message = FALSE}
mean_growth <- clean_growth %>%
group_by(treatment) %>%
summarise_at(vars(total_growth), list(mean = mean))
```


### Checking Distributions For Normality

```{r warning = FALSE, message = FALSE}

# Original 

shapiro.test(clean_growth$total_growth) # P value = 2.292e-06
descdist(clean_growth$total_growth)

# trying log transform

clean_log <- clean_growth %>%
  mutate(loggrowth = log2(total_growth))
shapiro.test(clean_log$loggrowth) # P value 0.006626

# trying to square root transform

clean_root <- clean_growth %>%
  mutate(rootgrowth = sqrt(total_growth))
shapiro.test(clean_root$rootgrowth) # P value = 0.008449 

# All attempts show our data varies significantly from normal, now trying fist dist function to find the best distribution.

hist(clean_root$rootgrowth)

fitDist(rootgrowth, data = clean_root, type = "realAll", try.gamlss = T)

fitDist(total_growth, data = clean_growth, type = "realAll", try.gamlss = T)

### Both show the best distribution is Skew Exponential Power type 2

mSEP2 <- histDist(clean_growth$total_growth, "SEP2", density = T, main = "Skew exp type 2")
```

#### Modelling
```{r warning = FALSE, message = FALSE}


# Running a Gamlss Model

gamlss.mod <- gamlss(total_growth ~ treatment + amt_cut_mm + mortality,
               family = SEP2(),
               data = model_growth,
               control = gamlss.control(n.cyc = 25))

# ran after 25 iterations when we removed worm_id as a random effect as per Dans advice

# Checking model 

summary(gamlss.mod)
plot(gamlss.mod)
residuals(gamlss.mod)


```

